### ISSUE TITLE
OPDS support

### ISSUE THREAD

**Issue by HLFH** [marsender/atoll-digital-library#1]
Hi,

We need OPDS support. It's the RSS standard for Ebooks. Even on Kindle, KOReader supports it: https://github.com/koreader/koreader

Thanks in advance,

**Comment by marsender** [comment]
Hi,
We are working on it, via one of these libraries:
- https://github.com/marsender/cops
- https://github.com/marsender/silex-cops
But the job is not finished yet !

**Comment by HLFH** [comment]
Hi,

@marsender Cool! As seen [here](http://www.mobileread.com/forums/showthread.php?t=239755), there is also these projets: https://sourceforge.net/projects/elibsrv/ and this one: https://github.com/Yetangitu/owncloud-apps 

It seems that will elibsrv, we don't need Calibre dependency, so it's a nice advantage.

**Comment by marsender** [comment]
Hi,

Thanks for this links.
I also don't like Calibre dependency...
In fact, cops and silex-cops don't use calibre itself but only calibre database.
So I use my own script "epub-loader" https://github.com/marsender/cops/tree/master/resources/epub-loader to parse epup directory and generate a Calibre database on the fly.

**Comment by marsender** [comment]
OPDS support is now ready.
Here is the url: http://atoll-digital-library.org/opds/
